services:
  - type: web
    name: dw-line-seizou-jisseki-bot
    runtime: docker
    plan: free
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: SPREADSHEET_ID
        value: "1PRDhGP_4xiO_ZjJP3NB9Id3PmaPa5W7hNyrqFQ5EyqM"
      - key: GROUP_VENUE_MAP
        sync: false
